// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/16 20:54:17
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/claude/portfolio2/sites/site-03-atelier-blanc/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/claude/portfolio2/sites/site-03-atelier-blanc/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/claude/portfolio2/sites/site-03-atelier-blanc/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/claude/portfolio2/sites/site-03-atelier-blanc/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/claude/portfolio2/sites/site-03-atelier-blanc/plugins/**/*.{js,ts,mjs}","C:/claude/portfolio2/sites/site-03-atelier-blanc/composables/**/*.{js,ts,mjs}","C:/claude/portfolio2/sites/site-03-atelier-blanc/utils/**/*.{js,ts,mjs}","C:/claude/portfolio2/sites/site-03-atelier-blanc/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/claude/portfolio2/sites/site-03-atelier-blanc/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/claude/portfolio2/sites/site-03-atelier-blanc/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/claude/portfolio2/sites/site-03-atelier-blanc/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;